#!/bin/bash

# cribbed from Mike Bostock [ https://github.com/topojson/world-atlas ], with minor alterations

rm -rvf world

# "Map subunits: Countries subdivided by non-contiguous units. Lower-48 + DC, Alaska, Hawaii. Mainland metropolitan France, Corsica...."

world_shp() {
  mkdir -p build
  curl -z build/ne_$1_admin_0_map_subunits.zip -o build/ne_$1_admin_0_map_subunits.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_map_subunits.zip
  unzip -od build build/ne_$1_admin_0_map_subunits.zip
  chmod a-x build/ne_$1_admin_0_map_subunits.*
}

world() {
  world_shp $1
  mkdir -p world
  geo2topo -q 1e5 -n countries=<( \
      shp2json -n build/ne_$1_admin_0_map_subunits.shp \
        | ndjson-map '(d.id = d.properties.adm0_a3, d.properties = { homepart: d.properties.homepart === 1.0, tiny: d.properties.tiny >= 0, continent: d.properties.continent }, d)' \
        | geostitch -n) \
    | topomerge land=countries \
    > world/$1.json
}

#world 110m
world 50m
