#!/bin/bash

if [[ -z $(git status -s) ]]
then
  git checkout gh-pages
  git rebase master

  jspm bundle index.js --inject --minify

  git add config.js build.*
  git commit --amend --no-edit
  git push github gh-pages --force

  git checkout master
else
  echo "Cannot stage with local changes in process" 1>&2
  exit 1
fi
